version: "4.0"

actions:

  generate_dataset_2017:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2017.csv.gz
      -- --season-year 2017
    outputs:
      highly_sensitive:
        dataset: output/dataset_2017.csv.gz

  generate_dataset_2018:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2018.csv.gz
      -- --season-year 2018
    outputs:
      highly_sensitive:
        dataset: output/dataset_2018.csv.gz

  generate_dataset_2019:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2019.csv.gz
      -- --season-year 2019
    outputs:
      highly_sensitive:
        dataset: output/dataset_2019.csv.gz

  generate_dataset_2020:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2020.csv.gz
      -- --season-year 2020
    outputs:
      highly_sensitive:
        dataset: output/dataset_2020.csv.gz

  generate_dataset_2021:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2021.csv.gz
      -- --season-year 2021
    outputs:
      highly_sensitive:
        dataset: output/dataset_2021.csv.gz

  generate_dataset_2022:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2022.csv.gz
      -- --season-year 2022
    outputs:
      highly_sensitive:
        dataset: output/dataset_2022.csv.gz

  generate_dataset_2023:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2023.csv.gz
      -- --season-year 2023
    outputs:
      highly_sensitive:
        dataset: output/dataset_2023.csv.gz

  generate_dataset_2024:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2024.csv.gz
      -- --season-year 2024
    outputs:
      highly_sensitive:
        dataset: output/dataset_2024.csv.gz

  generate_dataset_2025:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_2025.csv.gz
      -- --season-year 2025
    outputs:
      highly_sensitive:
        dataset: output/dataset_2025.csv.gz

